In [1]:
import numpy as np
a = np.random.randn(5)

print(a)

[0.6076399  0.37356923 0.10197396 0.64298695 0.70570898]


In [2]:
print(a.shape)

(5,)


In [3]:
print(a.T)

[0.6076399  0.37356923 0.10197396 0.64298695 0.70570898]


In [4]:
print(np.dot(a, a.T))

1.4306362706711242


In [6]:
a = np.random.randn(5,1)
print(a)

[[-0.36968165]
 [-1.85607001]
 [ 0.34738257]
 [-0.72305379]
 [-0.55492018]]


In [7]:
print(a.T)

[[-0.36968165 -1.85607001  0.34738257 -0.72305379 -0.55492018]]


In [8]:
print(np.dot(a, a.T))

[[ 0.13666452  0.68615502 -0.12842096  0.26729971  0.20514381]
 [ 0.68615502  3.4449959  -0.64476636  1.34203845  1.02997071]
 [-0.12842096 -0.64476636  0.12067465 -0.25117628 -0.1927696 ]
 [ 0.26729971  1.34203845 -0.25117628  0.52280678  0.40123714]
 [ 0.20514381  1.02997071 -0.1927696   0.40123714  0.30793641]]
